language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - build-tools-24.0.2
    - android-25
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

script:
    - . buildReleaseApp.sh
    - . upload_artifact.sh

notifications:
  email: true

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

