language: android

jdk:
 - openjdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'

script:
    - ./gradlew clean assemble --stacktrace --info

notifications:
  email: true

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

